In [14]:
import pandas as pd
import numpy as np

In [161]:
df=pd.read_csv("example.csv")
df2 = df.copy()
print(list(df.columns))

['SL.No', 'Attribute A', 'Attribute B', 'Attribute C']


In [3]:
print(df["SL.No"])

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
Name: SL.No, dtype: int64


In [4]:
print(list(df.iloc[0])) # printing rows

[1, 12.0, 44, 'A']


In [5]:
print(list(df.iloc[:,0])) #printing column data

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [6]:
print(df[0:2]) 

   SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A
1      2          NaN           22           B


In [7]:
df.head(4)


SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A
1      2          NaN           22           B
2      3         31.0           13           A
3      4         19.0           13           C

In [8]:
df.mean(axis=1) #along columns

/tmp/ipykernel_315664/1316249669.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis=1) #along columns


0     19.000000
1     12.000000
2     15.666667
3     12.000000
4     17.000000
5     25.500000
6     23.000000
7     36.000000
8     40.000000
9     45.333333
10    16.500000
11    34.333333
12    37.666667
13    15.666667
14    35.666667
dtype: float64

In [9]:
df.mean(axis=0)

/tmp/ipykernel_315664/2681518468.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis=0)


SL.No           8.000000
Attribute A    42.166667
Attribute B    31.733333
dtype: float64

In [10]:
k = df.groupby("Attribute C")
for x,y in k:
    print(x,y)

A     SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
2       3         31.0           13           A
4       5         22.0           24           A
10     11          NaN           22           A
12     13         33.0           67           A
B    SL.No  Attribute A  Attribute B Attribute C
1      2          NaN           22           B
7      8         22.0           78           B
9     10         81.0           45           B
C     SL.No  Attribute A  Attribute B Attribute C
3       4         19.0           13           C
5       6          NaN           45           C
6       7         41.0           21           C
11     12         56.0           35           C
13     14         21.0           12           C
14     15         78.0           14           C


In [42]:
df.fillna(int(df["Attribute A"].mean()))

SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         42.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         42.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21          42
9      10         81.0           45           B
10     11         42.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C

In [62]:
np.random.rand(1,4)

array([[0.77085409, 0.48493107, 0.02911156, 0.08652569]])

In [76]:
x= [1,2,3,4,5]
p = np.array(x)

In [91]:
df.head(11).tail(3)

SL.No  Attribute A  Attribute B Attribute C
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A

In [135]:
x = ((1,2,3),(1,3,2),(1,9,3))
print(type(x),np.shape(x))

<class 'tuple'> (3, 3)


In [110]:
def create_numpy_ones_array(shape):
    w = np.ones(np.shape(shape))
    return w

In [111]:
create_numpy_ones_array(x)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [117]:
def create_numpy_zeroes_array(shape):
    w = np.zeros(np.shape(shape))
    return w

In [118]:
create_numpy_zeroes_array(x)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [119]:
def create_identity_numpy_array(order):
    w = np.identity(order)
    return w

In [120]:
create_identity_numpy_array(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
def matrix_cofactor(array):
    w = np.linalg.det(array) * np.linalg.inv(array)
    return np.transpose(w)

In [136]:
matrix_cofactor(x)

array([[-9., -1.,  6.],
       [21.,  0., -7.],
       [-5.,  1.,  1.]])

In [151]:
q = np.random.rand(*np.shape(x))
l =q**2
print(q,'\n', l**0.5)


[[0.47282816 0.65227079 0.24185905]
 [0.03113006 0.54423235 0.36471018]
 [0.89233328 0.45934559 0.4186541 ]] 
 [[0.47282816 0.65227079 0.24185905]
 [0.03113006 0.54423235 0.36471018]
 [0.89233328 0.45934559 0.4186541 ]]


In [152]:
df.head()


SL.No  Attribute A  Attribute B Attribute C
0      1         12.0           44           A
1      2          NaN           22           B
2      3         31.0           13           A
3      4         19.0           13           C
4      5         22.0           24           A

In [159]:
for colname in df.columns:
    df[colname] = df[colname].fillna(df[colname].mode()[0])

In [163]:
df.head(15)


SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          NaN           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          NaN           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C